export const countries = [
    {
        name: "Select country",
        value: "",
        disabled: true,
        selected: true,
    },
    { name: "Algeria", value: "dz" },
    { name: "Cambodia", value: "kh" },
    { name: "Cameroon", value: "cm" },
    { name: "China", value: "cn" },
    { name: "Egypt", value: "eg" },
    { name: "Gabon", value: "ga" },
    { name: "Indonesia", value: "id" },
    { name: "Iraq", value: "iq" },
    { name: "Jordan", value: "jo" },
    { name: "Lebanon", value: "lb" },
    { name: "Republic of North Macedonia", value: "mk" },
    { name: "Madagascar", value: "mg" },
    { name: "Morocco", value: "ma" },
    { name: "Nigeria", value: "ng" },
    { name: "Philippines", value: "ph" },
    { name: "Republic of Congo", value: "cg" },
    { name: "Thailand", value: "th" },
    { name: "United Kingdom", value: "gb" },
    { name: "Uzbekistan", value: "uz" },
    { name: "Vietnam", value: "vn" },
    { name: "Kenya", value: "ke" },
    { name: "Tanzania", value: "tz" },
    { name: "Tunisia", value: "tn" },
];
export const cities = {
    dz: [{ cityName: "Oran" }, { cityName: "Annaba" }],
    kh: [{ cityName: "Phnom Penh" }],
    cm: [
        { cityName: "Douala" },
        { cityName: "Garoua" },
        { cityName: "Yaounde" },
    ],
    cn: [
        { cityName: "Beijing" },
        { cityName: "Changsha" },
        { cityName: "Chengdu" },
        { cityName: "Chongqing" },
        { cityName: "Fuzhou" },
        { cityName: "Guangzhou (Canton)" },
        { cityName: "Hangzhou" },
        { cityName: "Jinan" },
        { cityName: "Kunming" },
        { cityName: "Nanjing" },
        { cityName: "Shanghai" },
        { cityName: "Shenyang" },
        { cityName: "Shenzhen" },
        { cityName: "Wuhan" },
        { cityName: "Xi'an" },
    ],
    eg: [
        { cityName: "Alexandria" },
        { cityName: "El Tagamoa" },
        { cityName: "El-Sheikh Zayed" },
        { cityName: "Hurghada" },
    ],
    ga: [
        { cityName: "Franceville" },
        { cityName: "Libreville" },
        { cityName: "Port Gentil" },
    ],
    id: [{ cityName: "Jakarata" }],
    iq: [{ cityName: "Baghdad" }, { cityName: "Erbil" }, { cityName: "Mosul" }],
    jo: [{ cityName: "Amman" }],
    lb: [{ cityName: "Beirut" }],
    mk: [{ cityName: "Skopje" }],
    mg: [{ cityName: "Ivato" }],
    ma: [
        { cityName: "Agadir" },
        { cityName: "Casablanca" },
        { cityName: "Fes" },
        { cityName: "Marrakech" },
        { cityName: "Oujda" },
        { cityName: "Rabat" },
        { cityName: "Tanger" },
    ],
    ng: [{ cityName: "Abuja" }, { cityName: "Lagos Victoria Island" }],
    ph: [{ cityName: "Cebu" }, { cityName: "Manille" }],
    cg: [{ cityName: "Brazzaville" }, { cityName: "Pointe-Noire" }],
    th: [{ cityName: "Bangkok" }],
    gb: [
        { cityName: "Edinburgh" },
        { cityName: "London" },
        { cityName: "Manchester" },
    ],
    vn: [{ cityName: "Hanoi" }, { cityName: "Ho Chi Minh City" }],
};
